test travis bench

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -121,17 +121,12 @@ matrix:
       addons: *xcode7
 
 
-    # ##########################################################################
-    # # Benchmarks
-    # ##########################################################################
-    # - env: BENCHMARKS=true COMPILER=clang++-3.6 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
-    # - env: BENCHMARKS=true COMPILER=clang++-3.6 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
-
-    # - env: BENCHMARKS=true COMPILER=clang++-3.7 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
-    # - env: BENCHMARKS=true COMPILER=clang++-3.7 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
-
-    # - env: BENCHMARKS=true COMPILER=clang++-3.8 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
-    # - env: BENCHMARKS=true COMPILER=clang++-3.8 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
+    ##########################################################################
+    # Benchmarks
+    ##########################################################################
+    - env: BENCHMARKS=true COMPILER=clang++-3.6 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
+    - env: BENCHMARKS=true COMPILER=clang++-3.7 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
+    - env: BENCHMARKS=true COMPILER=clang++-3.8 CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release"
 
 
 branches:
@@ -179,6 +174,13 @@ install:
 
 before_script:
   ############################################################################
+  # Set the git identity (for pushing the documentation and the benchmarks)
+  ############################################################################
+  - git config --global user.name "Travis bot"
+
+
+
+  ############################################################################
   # Go back to the root of the project and setup the build directory
   ############################################################################
   - export CXX_FLAGS="${CXX_FLAGS} -Wall -Wextra -Werror"
@@ -190,8 +192,44 @@ before_script:
   - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" ..
 
 script:
-  - make benchmarks -k
-  - make tests -k
+  ############################################################################
+  # We only run the full benchmarks on `master` when we're not in a pull
+  # request, because otherwise it takes too much Travis resources. Otherwise,
+  # we only run partial benchmarks to make sure they compile and run properly.
+  #
+  # Note: The benchmarks associated to a version of the documentation are
+  #       stored in `doc/html/benchmarks/`.
+  ############################################################################
+  # 2a23abcabd9ad20bcbfcbbbc0bcde87ba95db7f6
+  - |
+    if [[ "${BENCHMARKS}" == "true" ]]; then
+      if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
+        (cd build && make benchmarks) || exit 1
+        compiler_slug=$(cd build && make travis_compiler_slug | grep 'travis_compiler_slug:' | cut -d ' ' -f 2)
+        config_slug=$(cd build && make travis_config_slug | grep 'travis_config_slug:' | cut -d ' ' -f 2)
+
+        # Suppress output to avoid leaking the token when the command fails
+        git clone https://fpelliccioni:${GITHUB_TOKEN}@github.com/tao-cpp/algorithm --depth 1 --branch=gh-pages doc/html &>/dev/null
+        rm -rf doc/html/benchmarks/${config_slug}/${compiler_slug}/
+        mkdir -p doc/html/benchmarks/${config_slug}/${compiler_slug}/
+        for benchmark in $(ls build/benchmark/*.json | grep -v ".erb"); do
+          cp ${benchmark} doc/html/benchmarks/${config_slug}/${compiler_slug}/
+        done
+
+        pushd doc/html
+        git add --all .
+        git commit --allow-empty -m "Update benchmarks to ${TRAVIS_COMMIT:0:7} for build type '${config_slug}' and compiler '${compiler_slug}'"
+        # Suppress output to avoid leaking the token
+        travis_retry git push origin gh-pages &>/dev/null
+        popd
+      else
+        export BOOST_HANA_JUST_CHECK_BENCHMARKS=true
+        (cd build && make benchmarks -j2)
+      fi
+    fi
+
+  # - make benchmarks -k
+  # - make tests -k
 
 notifications:
   email: false
